//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4927.
// 
namespace PDA_GUI.Server_Connection {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActivityMonitorSoap", Namespace="http://localhost:2345")]
    public partial class ActivityMonitor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ActivityMonitor() {
            this.Url = "http://128.153.180.31:81/ActivityMonitor/ActivityMonitor.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:2345/HelloWorld", RequestNamespace="http://localhost:2345", ResponseNamespace="http://localhost:2345", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:2345/UploadStats", RequestNamespace="http://localhost:2345", ResponseNamespace="http://localhost:2345", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UploadStats(User me, Stats stats) {
            this.Invoke("UploadStats", new object[] {
                        me,
                        stats});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadStats(User me, Stats stats, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadStats", new object[] {
                        me,
                        stats}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUploadStats(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:2345/GetTasks", RequestNamespace="http://localhost:2345", ResponseNamespace="http://localhost:2345", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DailyTask[] GetTasks(User me) {
            object[] results = this.Invoke("GetTasks", new object[] {
                        me});
            return ((DailyTask[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTasks(User me, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTasks", new object[] {
                        me}, callback, asyncState);
        }
        
        /// <remarks/>
        public DailyTask[] EndGetTasks(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DailyTask[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:2345")]
    public partial class User {
        
        private string usernameField;
        
        private string passwordField;
        
        private string userClassField;
        
        private int idNumberField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string UserClass {
            get {
                return this.userClassField;
            }
            set {
                this.userClassField = value;
            }
        }
        
        /// <remarks/>
        public int idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WalkingTask))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:2345")]
    public abstract partial class DailyTask {
        
        private int idDailyTaskField;
        
        private string dailyTaskClassField;
        
        private bool activeField;
        
        private System.DateTime dateField;
        
        /// <remarks/>
        public int idDailyTask {
            get {
                return this.idDailyTaskField;
            }
            set {
                this.idDailyTaskField = value;
            }
        }
        
        /// <remarks/>
        public string DailyTaskClass {
            get {
                return this.dailyTaskClassField;
            }
            set {
                this.dailyTaskClassField = value;
            }
        }
        
        /// <remarks/>
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:2345")]
    public partial class WalkingTask : DailyTask {
        
        private int stepsField;
        
        /// <remarks/>
        public int steps {
            get {
                return this.stepsField;
            }
            set {
                this.stepsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WalkingStats))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:2345")]
    public abstract partial class Stats {
        
        private string statsClassField;
        
        private System.DateTime startDateTimeField;
        
        private System.DateTime endDateTimeField;
        
        private int idStatisticsField;
        
        private int idDailyTaskField;
        
        /// <remarks/>
        public string StatsClass {
            get {
                return this.statsClassField;
            }
            set {
                this.statsClassField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int idStatistics {
            get {
                return this.idStatisticsField;
            }
            set {
                this.idStatisticsField = value;
            }
        }
        
        /// <remarks/>
        public int idDailyTask {
            get {
                return this.idDailyTaskField;
            }
            set {
                this.idDailyTaskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:2345")]
    public partial class WalkingStats : Stats {
        
        private int stepsField;
        
        /// <remarks/>
        public int steps {
            get {
                return this.stepsField;
            }
            set {
                this.stepsField = value;
            }
        }
    }
}
